// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML2 : ObservableObject
    {

    public bool Cach_Dung { get; set; }
    public bool Dang_Bao_Che { get; set; }
    public bool Don_Gia { get; set; }
    public bool Don_Vi_Tinh { get; set; }
    public bool Du_Phong { get; set; }
    public bool Duong_Dung { get; set; }
    public bool Ham_Luong { get; set; }
    public bool Id { get; set; }
    public bool Lieu_Dung { get; set; }
    public bool Ma_Bac_Si { get; set; }
    public bool Ma_Cskcb_Thuoc { get; set; }
    public bool Ma_Dich_Vu { get; set; }
    public bool Ma_Khoa { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_Nhom { get; set; }
    public bool Ma_Pp_CheBien { get; set; }
    public bool Ma_Pttt { get; set; }
    public bool Ma_Thuoc { get; set; }
    public bool Muc_Huong { get; set; }
    public bool Ngay_Th_Yl { get; set; }
    public bool Ngay_Yl { get; set; }
    public bool Nguon_Ctra { get; set; }
    public bool Pham_Vi { get; set; }
    public bool So_Dang_Ky { get; set; }
    public bool So_Luong { get; set; }
    public bool Stt { get; set; }
    public bool T_Bhtt { get; set; }
    public bool T_Bncct { get; set; }
    public bool T_Bntt { get; set; }
    public bool T_NguonKhac { get; set; }
     public bool T_NguonKhac_Cl { get; set; } 
    public bool T_NguonKhac_Nsnn { get; set; }
    public bool T_NguonKhac_Vtnn { get; set; }
    public bool T_NguonKhac_Vttn { get; set; }
    public bool Ten_Thuoc { get; set; }
    public bool Thanh_Tien_Bh { get; set; }
    public bool Thanh_Tien_Bv { get; set; }
    public bool Tt_Thau { get; set; }
    public bool Tyle_Tt_Bh { get; set; }
    public bool Vet_Thuong_Tp { get; set; }
    
    // Header error flag - true if any field has error
    public bool XML2Header { get; set; } = false;

    public bool HasAnyError => Cach_Dung || Dang_Bao_Che || Don_Gia || Don_Vi_Tinh || Du_Phong || Duong_Dung || Ham_Luong || Id || Lieu_Dung || Ma_Bac_Si || Ma_Cskcb_Thuoc || Ma_Dich_Vu || Ma_Khoa || Ma_Lk || Ma_Nhom || Ma_Pp_CheBien || Ma_Pttt || Ma_Thuoc || Muc_Huong || Ngay_Th_Yl || Ngay_Yl || Nguon_Ctra || Pham_Vi || So_Dang_Ky || So_Luong || Stt || T_Bhtt || T_Bncct || T_Bntt || T_NguonKhac || T_NguonKhac_Cl || T_NguonKhac_Nsnn || T_NguonKhac_Vtnn || T_NguonKhac_Vttn || Ten_Thuoc || Thanh_Tien_Bh || Thanh_Tien_Bv || Tt_Thau || Tyle_Tt_Bh || Vet_Thuong_Tp;
}
}