// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML15 : ObservableObject
    {

    public bool Bddt_Arv { get; set; }
    public bool Du_Phong { get; set; }
    public bool Ho_Ten { get; set; }
    public bool Id { get; set; }
    public bool Ket_Qua_Dtri_Lao { get; set; }
    public bool Loai_Dtri_Lao { get; set; }
    public bool Ma_Bn { get; set; }
    public bool Ma_Cskcb { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ngay_Bat_Dau_Dt_Ctx { get; set; }
    public bool Ngaybd_Dtri_Lao { get; set; }
    public bool Ngaykd_Hiv { get; set; }
    public bool Ngaykt_Dtri_Lao { get; set; }
    public bool Phacdo_Dtri_Lao { get; set; }
    public bool PhanLoai_Lao_Hiv { get; set; }
    public bool PhanLoai_Lao_Kt { get; set; }
    public bool PhanLoai_Lao_Ts { get; set; }
    public bool PhanLoai_Lao_ViTri { get; set; }
    public bool PhanLoai_Lao_Vk { get; set; }
    public bool So_Cccd { get; set; }
    public bool Stt { get; set; }

    public bool HasAnyError => Bddt_Arv || Du_Phong || Ho_Ten || Id || Ket_Qua_Dtri_Lao || Loai_Dtri_Lao || Ma_Bn || Ma_Cskcb || Ma_Lk || Ngay_Bat_Dau_Dt_Ctx || Ngaybd_Dtri_Lao || Ngaykd_Hiv || Ngaykt_Dtri_Lao || Phacdo_Dtri_Lao || PhanLoai_Lao_Hiv || PhanLoai_Lao_Kt || PhanLoai_Lao_Ts || PhanLoai_Lao_ViTri || PhanLoai_Lao_Vk || So_Cccd || Stt;
}
}