// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML14 : ObservableObject
    {

    public bool Chan_DoAn_Rv { get; set; }
    public bool Dia_Chi { get; set; }
    public bool Du_Phong { get; set; }
    public bool Gioi_Tinh { get; set; }
    public bool Gt_The_Den { get; set; }
    public bool Ho_Ten { get; set; }
    public bool Id { get; set; }
    public bool Ma_Bac_Si { get; set; }
    public bool Ma_Benh_Chinh { get; set; }
    public bool Ma_Benh_Kt { get; set; }
    public bool Ma_Benh_Yhct { get; set; }
    public bool Ma_Cskcb { get; set; }
    public bool Ma_DoiTuong_Kcb { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_The_Bhyt { get; set; }
    public bool Ma_Ttdv { get; set; }
    public bool Ngay_Ct { get; set; }
    public bool Ngay_Hen_Kl { get; set; }
    public bool Ngay_Ra { get; set; }
    public bool Ngay_Sinh { get; set; }
    public bool Ngay_Vao { get; set; }
    public bool Ngay_Vao_Noi_Tru { get; set; }
    public bool So_GiayHen_Kl { get; set; }

    public bool HasAnyError => Chan_DoAn_Rv || Dia_Chi || Du_Phong || Gioi_Tinh || Gt_The_Den || Ho_Ten || Id || Ma_Bac_Si || Ma_Benh_Chinh || Ma_Benh_Kt || Ma_Benh_Yhct || Ma_Cskcb || Ma_DoiTuong_Kcb || Ma_Lk || Ma_The_Bhyt || Ma_Ttdv || Ngay_Ct || Ngay_Hen_Kl || Ngay_Ra || Ngay_Sinh || Ngay_Vao || Ngay_Vao_Noi_Tru || So_GiayHen_Kl;
}
}