// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML7 : ObservableObject
    {

    public bool Chan_DoAn_Rv { get; set; }
    public bool Du_Phong { get; set; }
    public bool Ghi_Chu { get; set; }
    public bool Ho_Ten_Cha { get; set; }
    public bool Ho_Ten_Me { get; set; }
    public bool Id { get; set; }
    public bool Ma_Bs { get; set; }
    public bool Ma_Cha { get; set; }
    public bool Ma_Dinh_Chi_Thai { get; set; }
    public bool Ma_Khoa_Rv { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_Me { get; set; }
    public bool Ma_The_Tam { get; set; }
    public bool Ma_Ttdv { get; set; }
    public bool Ma_Yte { get; set; }
    public bool Ngay_Ct { get; set; }
    public bool Ngay_Ra { get; set; }
    public bool Ngay_Vao { get; set; }
    public bool NgoaiTru_DenNgay { get; set; }
    public bool NgoaiTru_TuNgay { get; set; }
    public bool NguyenNhan_DinhChi { get; set; }
    public bool Pp_DieuTri { get; set; }
    public bool So_Luu_Tru { get; set; }
    public bool So_Ngay_Nghi { get; set; }
    public bool Ten_Bs { get; set; }
    public bool ThoiGian_DinhChi { get; set; }
    public bool Tuoi_Thai { get; set; }

    public bool HasAnyError => Chan_DoAn_Rv || Du_Phong || Ghi_Chu || Ho_Ten_Cha || Ho_Ten_Me || Id || Ma_Bs || Ma_Cha || Ma_Dinh_Chi_Thai || Ma_Khoa_Rv || Ma_Lk || Ma_Me || Ma_The_Tam || Ma_Ttdv || Ma_Yte || Ngay_Ct || Ngay_Ra || Ngay_Vao || NgoaiTru_DenNgay || NgoaiTru_TuNgay || NguyenNhan_DinhChi || Pp_DieuTri || So_Luu_Tru || So_Ngay_Nghi || Ten_Bs || ThoiGian_DinhChi || Tuoi_Thai;
}
}