// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML5 : ObservableObject
    {

    public bool Dien_Bien_Ls { get; set; }
    public bool Du_Phong { get; set; }
    public bool Giai_DoAn_Benh { get; set; }
    public bool Hoi_Chan { get; set; }
    public bool Id { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Nguoi_Thuc_Hien { get; set; }
    public bool Phau_Thuat { get; set; }
    public bool Stt { get; set; }
    public bool Thoi_Diem_Dbls { get; set; }

    public bool HasAnyError => Dien_Bien_Ls || Du_Phong || Giai_DoAn_Benh || Hoi_Chan || Id || Ma_Lk || Nguoi_Thuc_Hien || Phau_Thuat || Stt || Thoi_Diem_Dbls;
}
}