// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML8 : ObservableObject
    {

    public bool Chan_DoAn_Rv { get; set; }
    public bool Chan_DoAn_Vao { get; set; }
    public bool Don_Vi { get; set; }
    public bool Du_Phong { get; set; }
    public bool Ghi_Chu { get; set; }
    public bool Ho_Ten_Cha { get; set; }
    public bool Ho_Ten_Me { get; set; }
    public bool Id { get; set; }
    public bool Ket_Qua_Dtri { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_Loai_Kcb { get; set; }
    public bool Ma_The_Tam { get; set; }
    public bool Ma_Ttdv { get; set; }
    public bool Ngay_ConChet { get; set; }
    public bool Ngay_Ct { get; set; }
    public bool Ngay_Ra { get; set; }
    public bool Ngay_SinhCon { get; set; }
    public bool Ngay_Vao { get; set; }
    public bool Nguoi_Giam_Ho { get; set; }
    public bool Pp_DieuTri { get; set; }
    public bool Qt_Benhly { get; set; }
    public bool So_ConChet { get; set; }
    public bool Tomtat_Kq { get; set; }

    public bool HasAnyError => Chan_DoAn_Rv || Chan_DoAn_Vao || Don_Vi || Du_Phong || Ghi_Chu || Ho_Ten_Cha || Ho_Ten_Me || Id || Ket_Qua_Dtri || Ma_Lk || Ma_Loai_Kcb || Ma_The_Tam || Ma_Ttdv || Ngay_ConChet || Ngay_Ct || Ngay_Ra || Ngay_SinhCon || Ngay_Vao || Nguoi_Giam_Ho || Pp_DieuTri || Qt_Benhly || So_ConChet || Tomtat_Kq;
}
}