// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML6 : ObservableObject
    {

    public bool Bddt_Arv { get; set; }
    public bool Dia_Chi { get; set; }
    public bool Du_Phong { get; set; }
    public bool Giai_DoAn_Lam_Sang { get; set; }
    public bool Gioi_Tinh { get; set; }
    public bool Id { get; set; }
    public bool Kq_Dtri_Lao { get; set; }
    public bool Kq_Xntl_Vr { get; set; }
    public bool Lan_Xn_Pcr { get; set; }
    public bool Loai_Dtri_Lao { get; set; }
    public bool Ly_Do_Chuyen_Phac_Do { get; set; }
    public bool Ma_Bac_Phac_Do { get; set; }
    public bool Ma_Bac_Phac_Do_Bd { get; set; }
    public bool Ma_Cskcb { get; set; }
    public bool Ma_Kq_Xn_Pcr { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_Loai_Bn { get; set; }
    public bool Ma_Lydo_Dtri { get; set; }
    public bool Ma_Lydo_Xntl_Vr { get; set; }
    public bool Ma_Phac_Do_Dieu_Tri { get; set; }
    public bool Ma_Phac_Do_Dieu_Tri_Bd { get; set; }
    public bool Ma_The_Bhyt { get; set; }
    public bool Ma_Tinh_Trang_Dk { get; set; }
    public bool Ma_Xu_Tri { get; set; }
    public bool Mahuyen_Cu_Tru { get; set; }
    public bool Matinh_Cu_Tru { get; set; }
    public bool Maxa_Cu_Tru { get; set; }
    public bool Ngay_Bat_Dau_Dt_Ctx { get; set; }
    public bool Ngay_Bat_Dau_Xu_Tri { get; set; }
    public bool Ngay_Chuyen_Phac_Do { get; set; }
    public bool Ngay_Ket_Thuc_Xu_Tri { get; set; }
    public bool Ngay_Kq_Xn_Pcr { get; set; }
    public bool Ngay_Kq_Xn_Tlvr { get; set; }
    public bool Ngay_Nhan_Tt_Mang_Thai { get; set; }
    public bool Ngay_Sinh { get; set; }
    public bool Ngay_Xn_Pcr { get; set; }
    public bool Ngay_Xn_Tlvr { get; set; }
    public bool Ngaybd_Dtri_Lao { get; set; }
    public bool Ngaykd_Hiv { get; set; }
    public bool Ngaykt_Dtri_Lao { get; set; }
    public bool Nhom_Doi_Tuong { get; set; }
    public bool Noi_Bddt_Arv { get; set; }
    public bool Noi_Lay_Mau_Xn { get; set; }
    public bool Noi_Xn_Kd { get; set; }
    public bool Phacdo_Dtri_Lao { get; set; }
    public bool Sang_Loc_Lao { get; set; }
    public bool So_Cccd { get; set; }
    public bool So_Ngay_Cap_Thuoc_Arv { get; set; }

    public bool HasAnyError => Bddt_Arv || Dia_Chi || Du_Phong || Giai_DoAn_Lam_Sang || Gioi_Tinh || Id || Kq_Dtri_Lao || Kq_Xntl_Vr || Lan_Xn_Pcr || Loai_Dtri_Lao || Ly_Do_Chuyen_Phac_Do || Ma_Bac_Phac_Do || Ma_Bac_Phac_Do_Bd || Ma_Cskcb || Ma_Kq_Xn_Pcr || Ma_Lk || Ma_Loai_Bn || Ma_Lydo_Dtri || Ma_Lydo_Xntl_Vr || Ma_Phac_Do_Dieu_Tri || Ma_Phac_Do_Dieu_Tri_Bd || Ma_The_Bhyt || Ma_Tinh_Trang_Dk || Ma_Xu_Tri || Mahuyen_Cu_Tru || Matinh_Cu_Tru || Maxa_Cu_Tru || Ngay_Bat_Dau_Dt_Ctx || Ngay_Bat_Dau_Xu_Tri || Ngay_Chuyen_Phac_Do || Ngay_Ket_Thuc_Xu_Tri || Ngay_Kq_Xn_Pcr || Ngay_Kq_Xn_Tlvr || Ngay_Nhan_Tt_Mang_Thai || Ngay_Sinh || Ngay_Xn_Pcr || Ngay_Xn_Tlvr || Ngaybd_Dtri_Lao || Ngaykd_Hiv || Ngaykt_Dtri_Lao || Nhom_Doi_Tuong || Noi_Bddt_Arv || Noi_Lay_Mau_Xn || Noi_Xn_Kd || Phacdo_Dtri_Lao || Sang_Loc_Lao || So_Cccd || So_Ngay_Cap_Thuoc_Arv;
}
}