// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML13 : ObservableObject
    {

    public bool Chan_DoAn_Rv { get; set; }
    public bool Chucdanh_Nguoi_Ht { get; set; }
    public bool Dau_Hieu_Ls { get; set; }
    public bool Dia_Chi { get; set; }
    public bool Du_Phong { get; set; }
    public bool Giay_Chuyen_Tuyen { get; set; }
    public bool Gioi_Tinh { get; set; }
    public bool Gt_The_Den { get; set; }
    public bool Ho_Ten { get; set; }
    public bool Hoten_Nguoi_Ht { get; set; }
    public bool Huong_Dieu_Tri { get; set; }
    public bool Id { get; set; }
    public bool Ma_Bac_Si { get; set; }
    public bool Ma_Benh_Chinh { get; set; }
    public bool Ma_Benh_Kt { get; set; }
    public bool Ma_Benh_Yhct { get; set; }
    public bool Ma_Cskcb { get; set; }
    public bool Ma_DanToc { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_Loai_Rv { get; set; }
    public bool Ma_Lydo_Ct { get; set; }
    public bool Ma_Nghe_Nghiep { get; set; }
    public bool Ma_Noi_Den { get; set; }
    public bool Ma_Noi_Di { get; set; }
    public bool Ma_QuocTich { get; set; }
    public bool Ma_The_Bhyt { get; set; }
    public bool Ma_Ttdv { get; set; }
    public bool Ngay_Ra { get; set; }
    public bool Ngay_Sinh { get; set; }
    public bool Ngay_Vao { get; set; }
    public bool Ngay_Vao_Noi_Tru { get; set; }
    public bool PhuongTien_Vc { get; set; }
    public bool Pp_Dieu_Tri { get; set; }
    public bool Pp_DieuTri { get; set; }
    public bool Qt_Benhly { get; set; }
    public bool So_ChuyenTuyen { get; set; }
    public bool So_HoSo { get; set; }
    public bool Ten_Dich_Vu { get; set; }
    public bool Ten_Thuoc { get; set; }
    public bool Tomtat_Kq { get; set; }

    public bool HasAnyError => Chan_DoAn_Rv || Chucdanh_Nguoi_Ht || Dau_Hieu_Ls || Dia_Chi || Du_Phong || Giay_Chuyen_Tuyen || Gioi_Tinh || Gt_The_Den || Ho_Ten || Hoten_Nguoi_Ht || Huong_Dieu_Tri || Id || Ma_Bac_Si || Ma_Benh_Chinh || Ma_Benh_Kt || Ma_Benh_Yhct || Ma_Cskcb || Ma_DanToc || Ma_Lk || Ma_Loai_Rv || Ma_Lydo_Ct || Ma_Nghe_Nghiep || Ma_Noi_Den || Ma_Noi_Di || Ma_QuocTich || Ma_The_Bhyt || Ma_Ttdv || Ngay_Ra || Ngay_Sinh || Ngay_Vao || Ngay_Vao_Noi_Tru || PhuongTien_Vc || Pp_Dieu_Tri || Pp_DieuTri || Qt_Benhly || So_ChuyenTuyen || So_HoSo || Ten_Dich_Vu || Ten_Thuoc || Tomtat_Kq;
}
}