// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML4 : ObservableObject
    {

    public bool Don_Vi_Do { get; set; }
    public bool Du_Phong { get; set; }
    public bool Gia_Tri { get; set; }
    public bool Id { get; set; }
    public bool Ket_Luan { get; set; }
    public bool Ma_Bs_Doc_Kq { get; set; }
    public bool Ma_Chi_So { get; set; }
    public bool Ma_Dich_Vu { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Mo_Ta { get; set; }
    public bool Ngay_Kq { get; set; }
    public bool Stt { get; set; }
    public bool Ten_Chi_So { get; set; }

    public bool HasAnyError => Don_Vi_Do || Du_Phong || Gia_Tri || Id || Ket_Luan || Ma_Bs_Doc_Kq || Ma_Chi_So || Ma_Dich_Vu || Ma_Lk || Mo_Ta || Ngay_Kq || Stt || Ten_Chi_So;
}
}