// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML3 : ObservableObject
    {

    public bool Don_Gia_Bh { get; set; }
    public bool Don_Gia_Bv { get; set; }
    public bool Don_Vi_Tinh { get; set; }
    public bool Du_Phong { get; set; }
    public bool Goi_Vtyt { get; set; }
    public bool Id { get; set; }
    public bool Ma_Bac_Si { get; set; }
    public bool Ma_Benh { get; set; }
    public bool Ma_Benh_Yhct { get; set; }
    public bool Ma_Dich_Vu { get; set; }
    public bool Ma_Giuong { get; set; }
    public bool Ma_Hieu_Sp { get; set; }
    public bool Ma_Khoa { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_May { get; set; }
    public bool Ma_Nhom { get; set; }
    public bool Ma_Pttt { get; set; }
    public bool Ma_Pttt_Qt { get; set; }
    public bool Ma_Vat_Tu { get; set; }
    public bool Ma_Xang_Dau { get; set; }
    public bool Muc_Huong { get; set; }
    public bool Ngay_Kq { get; set; }
    public bool Ngay_Th_Yl { get; set; }
    public bool Ngay_Yl { get; set; }
    public bool Nguoi_Thuc_Hien { get; set; }
    public bool Pham_Vi { get; set; }
    public bool Pp_Vo_Cam { get; set; }
    public bool So_Luong { get; set; }
    public bool Stt { get; set; }
    public bool T_Bhtt { get; set; }
    public bool T_Bncct { get; set; }
    public bool T_Bntt { get; set; }
    public bool T_NguonKhac { get; set; }
    public bool T_NguonKhac_Cl { get; set; }
    public bool T_NguonKhac_Nsnn { get; set; }
    public bool T_NguonKhac_Vtnn { get; set; }
    public bool T_NguonKhac_Vttn { get; set; }
    public bool T_TranTt { get; set; }
    public bool Tai_Su_Dung { get; set; }
    public bool Ten_Dich_Vu { get; set; }
    public bool Ten_Vat_Tu { get; set; }
    public bool Thanh_Tien_Bh { get; set; }
    public bool Thanh_Tien_Bv { get; set; }
    public bool Tt_Thau { get; set; }
    public bool Tyle_Tt_Bh { get; set; }
    public bool Tyle_Tt_Dv { get; set; }
    public bool Vet_Thuong_Tp { get; set; }
    public bool Vi_Tri_Th_Dvkt { get; set; }
    
    // Business rule validation errors
    public bool ViKhuẩn_NuoiCay_DinhDanh_Conflict { get; set; } = false;
    
    public bool XML3Header { get; set; } = false;
        public bool HasAnyError => Don_Gia_Bh || Don_Gia_Bv || Don_Vi_Tinh || Du_Phong || Goi_Vtyt || Id || Ma_Bac_Si || Ma_Benh || Ma_Benh_Yhct || Ma_Dich_Vu || Ma_Giuong || Ma_Hieu_Sp || Ma_Khoa || Ma_Lk || Ma_May || Ma_Nhom || Ma_Pttt || Ma_Pttt_Qt || Ma_Vat_Tu || Ma_Xang_Dau || Muc_Huong || Ngay_Kq || Ngay_Th_Yl || Ngay_Yl || Nguoi_Thuc_Hien || Pham_Vi || Pp_Vo_Cam || So_Luong || Stt || T_Bhtt || T_Bncct || T_Bntt || T_NguonKhac || T_NguonKhac_Cl || T_NguonKhac_Nsnn || T_NguonKhac_Vtnn || T_NguonKhac_Vttn || T_TranTt || Tai_Su_Dung || Ten_Dich_Vu || Ten_Vat_Tu || Thanh_Tien_Bh || Thanh_Tien_Bv || Tt_Thau || Tyle_Tt_Bh || Tyle_Tt_Dv || Vet_Thuong_Tp || Vi_Tri_Th_Dvkt || ViKhuẩn_NuoiCay_DinhDanh_Conflict;
}
}