// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML11 : ObservableObject
    {

    public bool Chan_DoAn_Rv { get; set; }
    public bool Den_Ngay { get; set; }
    public bool Don_Vi { get; set; }
    public bool Du_Phong { get; set; }
    public bool Ho_Ten_Cha { get; set; }
    public bool Ho_Ten_Me { get; set; }
    public bool Id { get; set; }
    public bool Ma_Bhxh { get; set; }
    public bool Ma_Bs { get; set; }
    public bool Ma_Dinh_Chi_Thai { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_The_Bhyt { get; set; }
    public bool Ma_The_Tam { get; set; }
    public bool Ma_Ttdv { get; set; }
    public bool Mau_So { get; set; }
    public bool Ngay_Ct { get; set; }
    public bool NguyenNhan_DinhChi { get; set; }
    public bool Pp_DieuTri { get; set; }
    public bool So_Ct { get; set; }
    public bool So_Kcb { get; set; }
    public bool So_Ngay_Nghi { get; set; }
    public bool So_Seri { get; set; }
    public bool Tu_Ngay { get; set; }
    public bool Tuoi_Thai { get; set; }

    public bool HasAnyError => Chan_DoAn_Rv || Den_Ngay || Don_Vi || Du_Phong || Ho_Ten_Cha || Ho_Ten_Me || Id || Ma_Bhxh || Ma_Bs || Ma_Dinh_Chi_Thai || Ma_Lk || Ma_The_Bhyt || Ma_The_Tam || Ma_Ttdv || Mau_So || Ngay_Ct || NguyenNhan_DinhChi || Pp_DieuTri || So_Ct || So_Kcb || So_Ngay_Nghi || So_Seri || Tu_Ngay || Tuoi_Thai;
}
}