// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML9 : ObservableObject
    {
    public bool Can_Nang_Con { get; set; }
    public bool Du_Phong { get; set; }
    public bool Ghi_Chu { get; set; }
    public bool Gioi_Tinh_Con { get; set; }
    public bool Ho_Ten_Cha { get; set; }
    public bool Ho_Ten_Con { get; set; }
    public bool Ho_Ten_Nnd { get; set; }
    public bool Id { get; set; }
    public bool Lan_Sinh { get; set; }
    public bool Ma_Bhxh_Nnd { get; set; }
    public bool Ma_DanToc_Nnd { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_QuocTich { get; set; }
    public bool Ma_The_Nnd { get; set; }
    public bool Ma_The_Tam { get; set; }
    public bool Ma_Ttdv { get; set; }
    public bool Mahuyen_Cu_Tru { get; set; }
    public bool Matinh_Cu_Tru { get; set; }
    public bool Maxa_Cu_Tru { get; set; }
    public bool Ngay_Ct { get; set; }
    public bool Ngay_Sinh_Con { get; set; }
    public bool Ngaycap_Cccd_Nnd { get; set; }
    public bool Ngaysinh_Nnd { get; set; }
    public bool Nguoi_Do_De { get; set; }
    public bool Nguoi_Ghi_Phieu { get; set; }
    public bool Noi_Cu_Tru_Nnd { get; set; }
    public bool Noi_Sinh_Con { get; set; }
    public bool Noicap_Cccd_Nnd { get; set; }
    public bool Quyen_So { get; set; }
    public bool Sinhcon_Duoi32Tuan { get; set; }
    public bool Sinhcon_PhauThuat { get; set; }
    public bool So { get; set; }
    public bool So_Cccd_Nnd { get; set; }
    public bool So_Con { get; set; }
    public bool So_Con_Song { get; set; }
    public bool Tinh_Trang_Con { get; set; }

    public bool HasAnyError => Can_Nang_Con || Du_Phong || Ghi_Chu || Gioi_Tinh_Con || Ho_Ten_Cha || Ho_Ten_Con || Ho_Ten_Nnd || Id || Lan_Sinh || Ma_Bhxh_Nnd || Ma_DanToc_Nnd || Ma_Lk || Ma_QuocTich || Ma_The_Nnd || Ma_The_Tam || Ma_Ttdv || Mahuyen_Cu_Tru || Matinh_Cu_Tru || Maxa_Cu_Tru || Ngay_Ct || Ngay_Sinh_Con || Ngaycap_Cccd_Nnd || Ngaysinh_Nnd || Nguoi_Do_De || Nguoi_Ghi_Phieu || Noi_Cu_Tru_Nnd || Noi_Sinh_Con || Noicap_Cccd_Nnd || Quyen_So || Sinhcon_Duoi32Tuan || Sinhcon_PhauThuat || So || So_Cccd_Nnd || So_Con || So_Con_Song || Tinh_Trang_Con;
}
}