// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML1 : ObservableObject
    {

    public bool Can_Nang { get; set; }
    public bool Can_Nang_Con { get; set; }
    public bool Chan_DoAn_Rv { get; set; }
    public bool Chan_DoAn_Vao { get; set; }
    public bool Dia_Chi { get; set; }
    public bool Dien_Thoai { get; set; }
    public bool Du_Phong { get; set; }
    public bool Ghi_Chu { get; set; }
    public bool Giay_Chuyen_Tuyen { get; set; }
    public bool Gioi_Tinh { get; set; }
    public bool Gt_The_Den { get; set; }
    public bool Gt_The_Tu { get; set; }
    public bool Ho_Ten { get; set; }
    public bool Id { get; set; }
    public bool Ket_Qua_Dtri { get; set; }
    public bool Ly_Do_Vnt { get; set; }
    public bool Ly_Do_Vv { get; set; }
    public bool Ma_Benh_Chinh { get; set; }
    public bool Ma_Benh_Kt { get; set; }
    public bool Ma_Benh_Yhct { get; set; }
    public bool Ma_Bn { get; set; }
    public bool Ma_Cskcb { get; set; }
    public bool Ma_DanToc { get; set; }
    public bool Ma_Dkbd { get; set; }
    public bool Ma_DoiTuong_Kcb { get; set; }
    public bool Ma_Hsba { get; set; }
    public bool Ma_Khoa { get; set; }
    public bool Ma_KhuVuc { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_Loai_Kcb { get; set; }
    public bool Ma_Loai_Rv { get; set; }
    public bool Ma_Ly_Do_Vnt { get; set; }
    public bool Ma_Nghe_Nghiep { get; set; }
    public bool Ma_Noi_Den { get; set; }
    public bool Ma_Noi_Di { get; set; }
    public bool Ma_Pttt_Qt { get; set; }
    public bool Ma_QuocTich { get; set; }
    public bool Ma_Tai_Nan { get; set; }
    public bool Ma_The_Bhyt { get; set; }
    public bool Ma_Ttdv { get; set; }
    public bool Mahuyen_Cu_Tru { get; set; }
    public bool Matinh_Cu_Tru { get; set; }
    public bool Maxa_Cu_Tru { get; set; }
    public bool Nam_Nam_Lien_Tuc { get; set; }
    public bool Nam_Qt { get; set; }
    public bool Ngay_Mien_Cct { get; set; }
    public bool Ngay_Ra { get; set; }
    public bool Ngay_Sinh { get; set; }
    public bool Ngay_Tai_Kham { get; set; }
    public bool Ngay_Ttoan { get; set; }
    public bool Ngay_Vao { get; set; }
    public bool Ngay_Vao_Noi_Tru { get; set; }
    public bool Nhom_Mau { get; set; }
    public bool Pp_Dieu_Tri { get; set; }
    public bool So_Cccd { get; set; }
    public bool So_Ngay_Dtri { get; set; }
    public bool Stt { get; set; }
    public bool T_Bhtt { get; set; }
    public bool T_Bhtt_Gdv { get; set; }
    public bool T_Bncct { get; set; }
    public bool T_Bntt { get; set; }
    public bool T_NguonKhac { get; set; }
    public bool T_Thuoc { get; set; }
    public bool T_TongChi_Bh { get; set; }
    public bool T_TongChi_Bv { get; set; }
    public bool T_Vtyt { get; set; }
    public bool Thang_Qt { get; set; }
    
    // Header error flag - true if any field has error
    public bool XML1Header { get; set; } = false;

    public bool HasAnyError => Can_Nang || Can_Nang_Con || Chan_DoAn_Rv || Chan_DoAn_Vao || Dia_Chi || Dien_Thoai || Du_Phong || Ghi_Chu || Giay_Chuyen_Tuyen || Gioi_Tinh || Gt_The_Den || Gt_The_Tu || Ho_Ten || Id || Ket_Qua_Dtri || Ly_Do_Vnt || Ly_Do_Vv || Ma_Benh_Chinh || Ma_Benh_Kt || Ma_Benh_Yhct || Ma_Bn || Ma_Cskcb || Ma_DanToc || Ma_Dkbd || Ma_DoiTuong_Kcb || Ma_Hsba || Ma_Khoa || Ma_KhuVuc || Ma_Lk || Ma_Loai_Kcb || Ma_Loai_Rv || Ma_Ly_Do_Vnt || Ma_Nghe_Nghiep || Ma_Noi_Den || Ma_Noi_Di || Ma_Pttt_Qt || Ma_QuocTich || Ma_Tai_Nan || Ma_The_Bhyt || Ma_Ttdv || Mahuyen_Cu_Tru || Matinh_Cu_Tru || Maxa_Cu_Tru || Nam_Nam_Lien_Tuc || Nam_Qt || Ngay_Mien_Cct || Ngay_Ra || Ngay_Sinh || Ngay_Tai_Kham || Ngay_Ttoan || Ngay_Vao || Ngay_Vao_Noi_Tru || Nhom_Mau || Pp_Dieu_Tri || So_Cccd || So_Ngay_Dtri || Stt || T_Bhtt || T_Bhtt_Gdv || T_Bncct || T_Bntt || T_NguonKhac || T_Thuoc || T_TongChi_Bh || T_TongChi_Bv || T_Vtyt || Thang_Qt;
}
}