// <auto-generated by NYRA />
using CommunityToolkit.Mvvm.ComponentModel;

namespace WPF_GiamDinhBaoHiem.Repos.Model {
public class ErrorXML10 : ObservableObject
    {

    public bool Chan_DoAn_Rv { get; set; }
    public bool Den_Ngay { get; set; }
    public bool Don_Vi { get; set; }
    public bool Du_Phong { get; set; }
    public bool Id { get; set; }
    public bool Ma_Bs { get; set; }
    public bool Ma_Lk { get; set; }
    public bool Ma_Ttdv { get; set; }
    public bool Ngay_Ct { get; set; }
    public bool So_Ct { get; set; }
    public bool So_Ngay { get; set; }
    public bool So_Seri { get; set; }
    public bool Ten_Bs { get; set; }
    public bool Tu_Ngay { get; set; }

    public bool HasAnyError => Chan_DoAn_Rv || Den_Ngay || Don_Vi || Du_Phong || Id || Ma_Bs || Ma_Lk || Ma_Ttdv || Ngay_Ct || So_Ct || So_Ngay || So_Seri || Ten_Bs || Tu_Ngay;
}
}