const mongoose = require('mongoose');

const XML1Schema = new mongoose.Schema({
  id:               { type: Number, required: false },
  Ma_Lk:            { type: String, default: null },
  Stt:              { type: Number, default: null },
  Ma_Bn:            { type: String, default: null },
  Ho_Ten:           { type: String, default: null },
  So_Cccd:          { type: String, default: null },
  Ngay_Sinh:        { type: String, default: null },
  Gioi_Tinh:        { type: Number, default: null },
  Ma_QuocTich:      { type: String, default: null },
  Ma_DanToc:        { type: String, default: null },
  Ma_Nghe_Nghiep:   { type: String, default: null },
  Dia_Chi:          { type: String, default: null },
  Matinh_Cu_Tru:    { type: String, default: null },
  Mahuyen_Cu_Tru:   { type: String, default: null },
  Maxa_Cu_Tru:      { type: String, default: null },
  Dien_Thoai:       { type: String, default: null },
  Ma_The_Bhyt:      { type: String, default: null },
  Ma_Dkbd:          { type: String, default: null },
  Gt_The_Tu:        { type: String, default: null },
  Gt_The_Den:       { type: String, default: null },
  Ngay_Mien_Cct:    { type: String, default: null },
  Ly_Do_Vv:         { type: String, default: null },
  Ly_Do_Vnt:        { type: String, default: null },
  Ma_Ly_Do_Vnt:     { type: String, default: null },
  Chan_DoAn_Vao:    { type: String, default: null },
  Chan_DoAn_Rv:     { type: String, default: null },
  Ma_Benh_Chinh:    { type: String, default: null },
  Ma_Benh_Kt:       { type: String, default: null },
  Ma_Benh_Yhct:     { type: String, default: null },
  Ma_Pttt_Qt:       { type: String, default: null },
  Ma_DoiTuong_Kcb:  { type: String, default: null },
  Ma_Noi_Di:        { type: String, default: null },
  Ma_Noi_Den:       { type: String, default: null },
  Ma_Tai_Nan:       { type: Number, default: null },
  Ngay_Vao:         { type: String, default: null },
  Ngay_Vao_Noi_Tru: { type: String, default: null },
  Ngay_Ra:          { type: String, default: null },
  Giay_Chuyen_Tuyen:{ type: String, default: null },
  So_Ngay_Dtri:     { type: Number, default: null },
  Pp_Dieu_Tri:      { type: String, default: null },
  Ket_Qua_Dtri:     { type: Number, default: null },
  Ma_Loai_Rv:       { type: Number, default: null },
  Ghi_Chu:          { type: String, default: null },
  Ngay_Ttoan:       { type: String, default: null },
  T_Thuoc:          { type: mongoose.Schema.Types.Decimal128, default: null },
  T_Vtyt:           { type: mongoose.Schema.Types.Decimal128, default: null },
  T_TongChi_Bv:     { type: mongoose.Schema.Types.Decimal128, default: null },
  T_TongChi_Bh:     { type: mongoose.Schema.Types.Decimal128, default: null },
  T_Bntt:           { type: mongoose.Schema.Types.Decimal128, default: null },
  T_Bncct:          { type: mongoose.Schema.Types.Decimal128, default: null },
  T_Bhtt:           { type: mongoose.Schema.Types.Decimal128, default: null },
  T_NguonKhac:      { type: mongoose.Schema.Types.Decimal128, default: null },
  T_Bhtt_Gdv:       { type: mongoose.Schema.Types.Decimal128, default: null },
  Nam_Qt:           { type: Number, default: null },
  Thang_Qt:         { type: Number, default: null },
  Ma_Loai_Kcb:      { type: String, default: null },
  Ma_Khoa:          { type: String, default: null },
  Ma_Cskcb:         { type: String, default: null },
  Ma_KhuVuc:        { type: String, default: null },
  Can_Nang:         { type: String, default: null },
  Can_Nang_Con:     { type: String, default: null },
  Nam_Nam_Lien_Tuc: { type: String, default: null },
  Ngay_Tai_Kham:    { type: String, default: null },
  Ma_Hsba:          { type: String, default: null },
  Ma_Ttdv:          { type: String, default: null },
  Du_Phong:         { type: String, default: null },
  Nhom_Mau:         { type: String, default: null }
}, {
  timestamps: true,
  strict: false
});

module.exports = mongoose.model('XML1', XML1Schema);
