const mongoose = require('mongoose');

const XML6Schema = new mongoose.Schema({
  id:                       { type: Number, required: false },
  Ma_Lk:                    { type: String, default: null },
  Ma_The_Bhyt:              { type: String, default: null },
  So_Cccd:                  { type: String, default: null },
  Ngaykd_Hiv:               { type: String, default: null },
  Bddt_Arv:                 { type: String, default: null },
  Ma_Phac_Do_Dieu_Tri_Bd:   { type: String, default: null },
  Ma_Bac_Phac_Do_Bd:        { type: Number, default: null },
  Ma_Lydo_Dtri:             { type: Number, default: null },
  Loai_Dtri_Lao:            { type: Number, default: null },
  Phacdo_Dtri_Lao:          { type: Number, default: null },
  Ngaybd_Dtri_Lao:          { type: String, default: null },
  Ngaykt_Dtri_Lao:          { type: String, default: null },
  Ma_Lydo_Xntl_Vr:          { type: Number, default: null },
  Ngay_Xn_Tlvr:             { type: String, default: null },
  Kq_Xntl_Vr:               { type: Number, default: null },
  Ngay_Kq_Xn_Tlvr:          { type: String, default: null },
  Ma_Loai_Bn:               { type: Number, default: null },
  Ma_Tinh_Trang_Dk:         { type: String, default: null },
  Lan_Xn_Pcr:               { type: Number, default: null },
  Ngay_Xn_Pcr:              { type: String, default: null },
  Ngay_Kq_Xn_Pcr:           { type: String, default: null },
  Ma_Kq_Xn_Pcr:             { type: Number, default: null },
  Ngay_Nhan_Tt_Mang_Thai:   { type: String, default: null },
  Ngay_Bat_Dau_Dt_Ctx:      { type: String, default: null },
  Ma_Xu_Tri:                { type: Number, default: null },
  Ngay_Bat_Dau_Xu_Tri:      { type: String, default: null },
  Ngay_Ket_Thuc_Xu_Tri:     { type: String, default: null },
  Ma_Phac_Do_Dieu_Tri:      { type: String, default: null },
  Ma_Bac_Phac_Do:           { type: Number, default: null },
  So_Ngay_Cap_Thuoc_Arv:    { type: Number, default: null },
  Du_Phong:                 { type: String, default: null },
  Ngay_Sinh:                { type: String, default: null },
  Gioi_Tinh:                { type: Number, default: null },
  Dia_Chi:                  { type: String, default: null },
  Matinh_Cu_Tru:            { type: String, default: null },
  Mahuyen_Cu_Tru:           { type: String, default: null },
  Maxa_Cu_Tru:              { type: String, default: null },
  Noi_Lay_Mau_Xn:           { type: String, default: null },
  Noi_Xn_Kd:                { type: String, default: null },
  Noi_Bddt_Arv:             { type: String, default: null },
  Sang_Loc_Lao:             { type: Number, default: null },
  Kq_Dtri_Lao:              { type: Number, default: null },
  Giai_DoAn_Lam_Sang:       { type: Number, default: null },
  Nhom_Doi_Tuong:           { type: Number, default: null },
  Ngay_Chuyen_Phac_Do:      { type: String, default: null },
  Ly_Do_Chuyen_Phac_Do:     { type: Number, default: null },
  Ma_Cskcb:                 { type: String, default: null }
}, {
  timestamps: true,
  strict: false
});

module.exports = mongoose.model('XML6', XML6Schema);
